lab9k/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('reservatie_open_cv.urls')),
    url(r'^admin/', admin.site.urls),
]

reservatie_open_cv/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'data/', views.data, name='data'),
    url(r'loading/', views.loading, name='loading'),
    url(r'confirmation/', views.confirmation, name='confirmation'),
    url(r'error/', views.error, name='error'),
    url(r'camera/', views.camerafunction, name='camera'),
    url(r'facerec/', views.facerec,name='facerec'),
    url(r'noRoom/', views.noRoom, name='noRoom'),
    url(r'noPerson/', views.noPerson, name='noPerson'),
    url(r'accept/',views.accept,name='accept')
]

reservatie_open_cv/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class FaceUser(User):
    face_id = models.IntegerField(blank=False, default=9999999, db_index=True, unique=True)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Zaal(models.Model):
    """
    This model represents a room, which can be reserved by Users
    """
    # name of the room (roomnumber e.g. : D01.24A)
    naam = models.CharField(max_length=100, blank=False)
    # location of the room, can be an address, or university campus, building, etc.
    locatie = models.CharField(max_length=100, blank=False)
    # amount of spots in the room
    aantal_plaatsen = models.IntegerField(default=0)

    def __str__(self):
        return self.locatie + " : " + self.naam

    def is_vrij_op_datum(self, datum):
        """

        :type datum: datetime
        """
        reservatie = self.reservaties.filter(date=datum.date())
        if reservatie:
            return False
        return True


class Reservatie(models.Model):
    """
    This model represents a reservation for a room, the object holds relations to the user, who made the reservation,
    And the room, where the meeting will be held.
    """
    # user who created the reservation
    face_user = models.ForeignKey(FaceUser)
    # date and time the meeting will be held
    date = models.DateTimeField(null=False, blank=False)
    # date and time the reservation was first made
    created = models.DateTimeField(auto_now_add=True)
    # date and time the reservation was last updated
    updated = models.DateTimeField(auto_now=True)
    # room the reservation will be held in
    for_zaal = models.ForeignKey(Zaal, on_delete=models.CASCADE, related_name='reservaties')

    def __str__(self):
        return "Reservatie: " + str(self.date) + " door user: " + str(self.face_user)

reservatie_open_cv/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import camera
from datetime import datetime
from subprocess import call
from .models import Zaal, User, Reservatie, FaceUser
import recognize
import face_detection
import json
import mailgun
from django.http import HttpResponse
import time


def index(request):
    # open the index page
    return render(request, 'reservatie_open_cv/index.html')


def data(request):
    # open the data page
    return render(request, 'reservatie_open_cv/data.html')


def loading(request):
    # this methode check get called twice,
    # first time to check if there is a room free if not back to time and date
    # second time to proceed(so free room) and go to the imagetaker
    if request.method == "POST":
        timestamp = float(request.POST.get('date_value'))
        date = datetime.fromtimestamp(timestamp / 1e3)
        alle_zalen = Zaal.objects.all()
        gekozen_zaal = None
        for zaal in alle_zalen:
            if zaal.is_vrij_op_datum(date):
                gekozen_zaal = zaal
                break
        if gekozen_zaal is None:
            return render(request, "reservatie_open_cv/noRooms.html")
        response = render(request, 'reservatie_open_cv/loading.html')
        response.set_cookie(key='gekozen_zaal', value=gekozen_zaal.naam)
        response.set_cookie(key='datum', value=timestamp)
        return response
    # TODO: mag misschien weg herbekijken
    if request.method == "GET":
        return render(request, 'reservatie_open_cv/loading.html')


def confirmation(request):
    # person data is alright now all we need is his confirmation
    # send page where we display the data and some buttons
    date = datetime.fromtimestamp(float(request.COOKIES.get('datum')) / 1e3)
    room = request.COOKIES.get('gekozen_zaal')
    name = request.COOKIES.get('naam')
    return render(request, 'reservatie_open_cv/confirmation.html',
                  {'name': name, 'room': room, 'date': date})


@csrf_exempt
def accept(request):
    # user confirmed so mail and save the reservation

    # TODO hier + mailen
    mailAddress = request.COOKIES.get('mail')
    date = request.COOKIES.get('datum')
    room = request.COOKIES.get('gekozen_zaal')
    name = request.COOKIES.get('naam')

    text = 'Beste ' + name + ',\nVolgende zaal: ' + room + 'werd voor u gereserveerd op ' + date + '.\n\nMet vriendelijke groeten,\nLab9000'
    mailgun.send_async_message('postmaster@mail.lab9k.gent', mailAddress,
                               'zaalboeking', "")

    zaal = request.COOKIES.get('gekozen_zaal')
    date = datetime.fromtimestamp(float(request.COOKIES.get('datum')) / 1e3)

    db_zaal = Zaal.objects.filter(naam=zaal).first()
    db_user = FaceUser.objects.filter(first_name=name).first()
    reservatie = Reservatie(for_zaal=db_zaal, date=date, face_user=db_user)
    reservatie.save()

    response = render(request, 'reservatie_open_cv/index.html')
    response.delete_cookie('datum')
    response.delete_cookie('gekozen_zaal')
    response.delete_cookie('naam')
    response.delete_cookie('mail')

    return response


@csrf_exempt
def error(request):
    # get called when a error occurs or unable to detect face
    return render(request, 'reservatie_open_cv/error.html')


@csrf_exempt
def noRoom(request):
    # no space available
    return render(request, 'reservatie_open_cv/noRooms.html')


@csrf_exempt
def noPerson(request):
    # person not recognized
    return render(request, 'reservatie_open_cv/noPerson.html')


@csrf_exempt
def camerafunction(request):
    # call methode for detecting face
    datacam = face_detection.take_picture()
    return JsonResponse(datacam)


@csrf_exempt
def facerec(request):
    # turn out their is a face on the image, so we have to detect whose face
    # it is

    x = request.POST.get('Coords[x]')
    y = request.POST.get('Coords[y]')
    h = request.POST.get('Coords[h]')
    w = request.POST.get('Coords[w]')
    face_id = recognize.recon(request.POST.get('Time'), (x, y, h, w))
    # if we detect one we can proceed else persoon not found
    if face_id == "Unknown":
        ret = {'naam': "None"}

        response = JsonResponse(ret)
        response.set_cookie(key='naam', value="None")
        response.set_cookie(key='mail', value="None")
        return response
    else:
        # cause images in the trainer.yml need an integer as id
        face_id = int(face_id)
        user = FaceUser.objects.get(face_id=face_id)
        ret = {'naam': user.first_name}

        response = JsonResponse(ret)
        response.set_cookie(key='naam', value=user.first_name)
        response.set_cookie(key='mail', value=user.email)
        return response

reservatie_open_cv/templates/reservatie_open_cv/confirmation.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'reservatie_open_cv/css/materialize.min.css' %}"
          media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <style>
        p {
            font-size: 1.2em;
        }
    </style>
</head>

<body class="amber">
<main class="container valign-wrapper" style="height: 99vh;">
    <div class="row">
        <div class="col s12 m6" style="margin: 0 auto; float: none; position: relative;
    top: 13px;">
            <div class="card">
                <div class="card-image"><img id= "personImg" src="https://www.equifax.com.au/sites/default/files/styles/image_1119x999/public/field/image/identity-watch-identity-theft_0.jpg?itok=TKmb0wNq"> <span class="card-title">Bevestig uw identiteit.</span> <a
                        href="{% url 'main:accept' %}" class="btn-floating btn-large halfway-fab waves-effect waves-light green"><i
                        class="material-icons">check</i></a></div>
                <div class="card-content">
                    <p class="left-align" style="font-size: 1.5em;">Naam: {{ name }}
                    </p>
                    <p class="left-align" style="font-size: 1em;">Datum: {{ date }}
                    </p>
                    <p class="left-align" style="font-size: 1em;">Zaal: {{ room }}
                    </p>
                    <a class="waves-effect waves-teal" href="{% url 'main:data' %}">Dit klopt niet, probeer opnieuw.</a>
                </div>
            </div>
        </div>
    </div>
</main>
     <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
     <script type="text/javascript" src="{% static 'reservatie_open_cv/js/materialize.min.js' %}"></script>
</body>

</html>

reservatie_open_cv/templates/reservatie_open_cv/data.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Date and Time Picker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">


    <link rel="stylesheet" href="{% static 'reservatie_open_cv/css/style.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'reservatie_open_cv/css/materialize.min.css' %}"
          media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body class="amber">
<main class="container valign-wrapper" style="height: 99vh;">
    <div class="app-container" ng-app="dateTimeApp" ng-controller="dateTimeCtrl as ctrl" ng-cloak>

        <div date-picker datepicker-title="Kies een datum voor uw reservatie" picktime="true" pickdate="true"
             pickpast="false" mondayfirst="false" custom-message="Je hebt gekozen voor:"
             selecteddate="ctrl.selected_date" updatefn="ctrl.updateDate(newdate)">

            <div class="datepicker" ng-class="{
				'am': timeframe == 'am',
				'pm': timeframe == 'pm',
				'compact': compact
			}">
                <div class="datepicker-header">
                    {% verbatim angular %}
                        <div class="datepicker-title" ng-if="datepicker_title">{{ datepickerTitle }}</div>
                        <div class="datepicker-subheader">{{ customMessage }} {{ selectedDay }}
                            {{ monthNames[localdate.getMonth()] }} {{ localdate.getDate() }}, {{ localdate.getFullYear()
                                    }}
                        </div>
                    {% endverbatim angular %}
                </div>
                <div class="datepicker-calendar">
                    <div class="calendar-header">
                        <div class="goback" ng-click="moveBack()" ng-if="pickdate">
                            <svg width="30" height="30">
                                <path fill="none" stroke="#0DAD83" stroke-width="3" d="M19,6 l-9,9 l9,9"></path>
                            </svg>
                        </div>
                        {% verbatim angular %}
                            <div class="current-month-container">{{ currentViewDate.getFullYear() }}
                                {{ currentMonthName() }}
                            </div>
                        {% endverbatim angular %}
                        <div class="goforward" ng-click="moveForward()" ng-if="pickdate">
                            <svg width="30" height="30">
                                <path fill="none" stroke="#0DAD83" stroke-width="3" d="M11,6 l9,9 l-9,9"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="calendar-day-header">
                        <span ng-repeat="day in days" class="day-label">{{ day.short }}</span>
                    </div>
                    {% verbatim angular %}
                        <div class="calendar-grid" ng-class="{false: 'no-hover'}[pickdate]">
                            <div ng-class="{'no-hover': !day.showday}" ng-repeat="day in month" class="datecontainer"
                                 ng-style="{'margin-left': calcOffset(day, $index)}"
                                 track by $index>
                                <div class="datenumber" ng-class="{'day-selected': day.selected }"
                                     ng-click="selectDate(day)">
                                    {{ day.daydate }}
                                </div>
                            </div>
                        </div>
                    {% endverbatim angular %}
                </div>
                {% verbatim angular %}
                    <div class="timepicker" ng-if="picktime == 'true'">
                        <div ng-class="{'am': timeframe == 'am', 'pm': timeframe == 'pm' }">
                            <div class="timepicker-container-outer" selectedtime="time" timetravel>
                                <div class="timepicker-container-inner">
                                    <div class="timeline-container" ng-mousedown="timeSelectStart($event)"
                                         sm-touchstart="timeSelectStart($event)">
                                        <div class="current-time">
                                            <div class="actual-time">{{ time }}</div>
                                        </div>
                                        <div class="timeline">
                                        </div>
                                        <div class="hours-container">
                                            <div class="hour-mark" ng-repeat="hour in getHours() track by $index"></div>
                                        </div>
                                    </div>
                                    <div class="display-time">
                                        <div class="decrement-time" ng-click="adjustTime('decrease')">
                                            <svg width="24" height="24">
                                                <path stroke="white" stroke-width="2" d="M8,12 h8"></path>
                                            </svg>
                                        </div>
                                        <div class="time" ng-class="{'time-active': edittime.active}">
                                            <input type="text" class="time-input" ng-model="edittime.input"
                                                   ng-keydown="changeInputTime($event)"
                                                   ng-focus="edittime.active = true; edittime.digits = [];"
                                                   ng-blur="edittime.active = false"/>
                                            <div class="formatted-time">{{ edittime.formatted }}</div>
                                        </div>
                                        <div class="increment-time" ng-click="adjustTime('increase')">
                                            <svg width="24" height="24">
                                                <path stroke="white" stroke-width="2" d="M12,7 v10 M7,12 h10"></path>
                                            </svg>
                                        </div>
                                    </div>
                                    <div class="am-pm-container">
                                        <div class="am-pm-button" ng-click="changetime('am');">am</div>
                                        <div class="am-pm-button" ng-click="changetime('pm');">pm</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endverbatim angular %}
                <form method="post" action="{% url 'main:loading' %}">
                    {% csrf_token %}
                    <input id="date_value" name="date_value" type="hidden">
                    <div class="buttons-container">
                        <div class="cancel-button"><a href="{% url 'main:data' %}" class="waves-effect waves-teal btn-flat">Cancel</a></div>
                        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                            <i class="material-icons right">send</i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.2/angular.min.js'></script>
<script type="text/javascript" src="{% static 'reservatie_open_cv/js/materialize.min.js' %}"></script>

<script src="{% static 'reservatie_open_cv/js/index.js' %}"></script>

</body>

</html>

reservatie_open_cv/templates/reservatie_open_cv/error.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'reservatie_open_cv/css/materialize.min.css' %}"
          media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> </head>

<body class="amber">
     <main class="container valign-wrapper" style="height: 99vh;">
        <div class="row">
        <div class="col s13 m7" style="margin: 0 auto; float: none; position: relative;
    top: 13px;">
            <div class="card">
                <div class="card-image"><img src="{% static 'reservatie_open_cv/img/cam.jpg' %}">
                       <a href="{% url 'main:data' %}" class="btn-floating btn-large halfway-fab waves-effect waves-light orange"><i
                        class="material-icons">check</i></a></div>
                <div class="card-content">
                    <p class="left-align" style="font-size: 1em;">Er is iets misgegaan bij het nemen van de foto, er kon geen gezicht gevonden worden. Gelieve het opnieuw te proberen.
                    </p>
                </div>
                </div>
            </div>
        </div>
    </div>


    </main>
     <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
     <script type="text/javascript" src="{% static 'reservatie_open_cv/js/materialize.min.js' %}"></script>
</body>

</html>

reservatie_open_cv/templates/reservatie_open_cv/index.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'reservatie_open_cv/css/materialize.min.css' %}"
          media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body class="amber">
<main class="container valign-wrapper" style="height: 99vh;">
    <div class="row">
        <div class="col s12 m6" style="margin: 0 auto; float: none;">
            <div class="card">
                <div class="card-image"><img src="{% static 'reservatie_open_cv/img/sample-1.jpg' %}">
                    <span class="card-title">Reserveer</span>
                    <a href="{% url 'main:data' %}"
                       class="btn-floating btn-large halfway-fab waves-effect waves-light red">
                        <i class="material-icons">date_range</i>
                    </a>
                </div>
                <div class="card-content">
                    <p class="left-align">Maak een nieuwe reservatie voor een van de zalen.<br> Selecteer een datum dat
                        past en kijk naar de camera.<br>Deze zal je herkennen zodat je u niet meer hoeft in te loggen.
                    </p>
                </div>
            </div>
        </div>
    </div>
</main>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{% static 'reservatie_open_cv/js/materialize.min.js' %}"></script>
</body>

</html>

reservatie_open_cv/templates/reservatie_open_cv/loading.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'reservatie_open_cv/css/materialize.min.css' %}"
          media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body class="amber">
<main class="container valign-wrapper" style="height: 99vh;">
    <div class="row">
        <div class="col s12 m6" style="margin: 0 auto; float: none;">
            <div class="card">
                <div class="card-image"><img src="{% static 'reservatie_open_cv/img/avatar.jpg' %}"></div>
                <div class="progress" style="margin: 0; border-radius: 0px;">
                    <div class="indeterminate"></div>
                </div>

                <div class="card-content">
                    <p class="left-align" id="textCam">Gelieve u frontaal voor de camera te plaatsen en lang genoeg stil
                        te staan.<br>
                        Uw gezicht wordt gescand en u wordt geauthoriseerd.</p>
                    <p class="left-align">{{ gekozen_zaal.naam }} {{ gekozen_zaal.aantal_plaatsen }}</p>
                    <p class="left-align">{{ datum }}</p>
                </div>
            </div>
        </div>
    </div>
</main>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{% static 'reservatie_open_cv/js/materialize.min.js' %}"></script>
<script type="text/javascript" src="{% static 'reservatie_open_cv/js/camera.js' %}"></script>
</body>

</html>

reservatie_open_cv/templates/reservatie_open_cv/noPerson.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'reservatie_open_cv/css/materialize.min.css' %}"
          media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> </head>

<body class="amber">
     <main class="container valign-wrapper" style="height: 99vh;">
        <div class="row">
        <div class="col s13 m7" style="margin: 0 auto; float: none; position: relative;
    top: 13px;">
            <div class="card">
                <div class="card-image"><img src="{% static 'reservatie_open_cv/img/unknown.png' %}">
                       <a href="{% url 'main:index' %}" class="btn-floating btn-large halfway-fab waves-effect waves-light orange"><i
                        class="material-icons">check</i></a></div>
                <div class="card-content">
                    <p class="left-align" style="font-size: 1em;">U werd niet herkend. Gelieve het reserveringsproces opnieuw te starten.
                    </p>
                </div>
                </div>
            </div>
        </div>
    </div>


    </main>
     <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
     <script type="text/javascript" src="{% static 'reservatie_open_cv/js/materialize.min.js' %}"></script>
</body>

</html>

reservatie_open_cv/templates/reservatie_open_cv/noRooms.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'reservatie_open_cv/css/materialize.min.css' %}"
          media="screen,projection"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> </head>

<body class="amber">
     <main class="container valign-wrapper" style="height: 99vh;">
        <div class="row">
        <div class="col s13 m7" style="margin: 0 auto; float: none; position: relative;
    top: 13px;">
            <div class="card">
                <div class="card-image"><img src="{% static 'reservatie_open_cv/img/calendar.PNG' %}">
                       <a href="{% url 'main:data' %}" class="btn-floating btn-large halfway-fab waves-effect waves-light orange"><i
                        class="material-icons">check</i></a></div>
                <div class="card-content">
                    <p class="left-align" style="font-size: 1em;">Op het door u geselecteerde moment is geen zaal meer beschikbaar, gelieve een ander tijdstip te kiezen.
                    </p>
                </div>
                </div>
            </div>
        </div>
    </div>


    </main>
     <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
     <script type="text/javascript" src="{% static 'reservatie_open_cv/js/materialize.min.js' %}"></script>
</body>

</html>